/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import Datos.Libros;
import Utilidades.Orden;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel Andrade
 */
public class Ventana extends javax.swing.JFrame {

    private List<Libros> listaLibros;

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setTitle("AppLibros");
        listaLibros = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        cajaNombre = new javax.swing.JTextField();
        cajaAutor = new javax.swing.JTextField();
        cajaGenero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaOrdenada = new javax.swing.JTextArea();
        ordenar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaSinOrdenar = new javax.swing.JTextArea();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jToggleButton1.setText("jToggleButton1");

        jToggleButton2.setText("jToggleButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        cajaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaNombreActionPerformed(evt);
            }
        });
        jPanel2.add(cajaNombre);
        cajaNombre.setBounds(140, 60, 160, 22);
        cajaNombre.getAccessibleContext().setAccessibleName("Nombre");

        cajaAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaAutorActionPerformed(evt);
            }
        });
        jPanel2.add(cajaAutor);
        cajaAutor.setBounds(140, 120, 160, 22);
        cajaAutor.getAccessibleContext().setAccessibleName("Autor");

        cajaGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaGeneroActionPerformed(evt);
            }
        });
        jPanel2.add(cajaGenero);
        cajaGenero.setBounds(140, 90, 160, 22);
        cajaGenero.getAccessibleContext().setAccessibleName("Genero");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombre del libro:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 60, 130, 20);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Genero:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 90, 130, 20);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Autor:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 120, 130, 20);

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        jPanel2.add(agregar);
        agregar.setBounds(340, 60, 90, 30);

        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btSalir);
        btSalir.setBounds(360, 530, 100, 20);

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("LISTA ORDENADA");
        jLabel7.setToolTipText("");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(120, 360, 230, 30);

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("LIBROS");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(40, 10, 110, 30);

        listaOrdenada.setColumns(20);
        listaOrdenada.setRows(5);
        jScrollPane1.setViewportView(listaOrdenada);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 400, 410, 120);

        ordenar.setText("Ordenar");
        ordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenarActionPerformed(evt);
            }
        });
        jPanel2.add(ordenar);
        ordenar.setBounds(340, 110, 90, 30);

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("LISTA DE LIBROS");
        jLabel9.setToolTipText("");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(110, 180, 230, 30);

        listaSinOrdenar.setColumns(20);
        listaSinOrdenar.setRows(5);
        jScrollPane2.setViewportView(listaSinOrdenar);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(20, 220, 410, 120);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 10, 470, 560);

        setSize(new java.awt.Dimension(507, 590));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_btSalirActionPerformed

    private void cajaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaNombreActionPerformed

    private void cajaAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaAutorActionPerformed

    private void cajaGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaGeneroActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        ingresar();
    }//GEN-LAST:event_agregarActionPerformed

    private void ordenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenarActionPerformed
        ordenar(listaLibros);
    }//GEN-LAST:event_ordenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JButton btSalir;
    private javax.swing.JTextField cajaAutor;
    private javax.swing.JTextField cajaGenero;
    private javax.swing.JTextField cajaNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTextArea listaOrdenada;
    private javax.swing.JTextArea listaSinOrdenar;
    private javax.swing.JButton ordenar;
    // End of variables declaration//GEN-END:variables

    private void ingresar() {
        String nombre = cajaNombre.getText();
        String autor = cajaAutor.getText();
        String genero = cajaGenero.getText();
        //String n = nombre.toUpperCase().charAt(0) + nombre.substring(1, nombre.length()).toLowerCase();
        //String a = autor.toUpperCase().charAt(0) + autor.substring(1, autor.length()).toLowerCase();
        //String g = genero.toUpperCase().charAt(0) + genero.substring(1, genero.length()).toLowerCase();
        Libros nuevoLibro = new Libros(nombre, autor, genero);
        listaLibros.add(nuevoLibro);
        actualizaListado1(listaLibros);
    }

    private void actualizaListado1(List<Libros> listas) {
        StringBuilder lista = new StringBuilder();
        for (Libros libros : listas) {
            lista.append(libros.toString()).append("\n");
        }
        listaSinOrdenar.setText(lista.toString());
    }

    private void actualizaListado2(List<Libros> listas) {
        StringBuilder lista = new StringBuilder();
        for (Libros libros : listas) {
            lista.append(libros.toString()).append("\n");
        }
        listaOrdenada.setText(lista.toString());
    }

    private void ordenar(List<Libros> lista) {
        Orden orden = new Orden();
        orden.bubbleSortArray(lista);
        actualizaListado2(lista);
    }

    private void salir() {
        System.exit(0);
    }
}
